---
title: "Additional Material"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Additional Material}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Additional material for Pig Science Breeding in SS 2023.


## Slides

```{r, echo=FALSE, message=FALSE, warning=FALSE}
s_sl_url <- "https://charlotte-ngs.github.io/psbss2023/sl/"
tbl_sl <- tibble::tibble(Nr = c(1, 2),
                         Date = c("2023-03-15",
                                  "2023-04-19"),
                         Topic = c(
                           paste0("[Introduction](", s_sl_url, "l01_psb_intro.pdf)", collapse = ""),
                           paste0("[Genomic Selection For a New Trait](", s_sl_url, "l02_psb_modsel_varcomp.pdf)", collapse = "")
                         ))
knitr::kable(tbl_sl)
```


## OHP Pictures

```{r, echo=FALSE, message=FALSE, warning=FALSE}
s_ohp_url <- "https://charlotte-ngs.github.io/psbss2023/ohp/"
tbl_ohp <- tibble::tibble(Nr = c(1, 2),
                         Date = c("2023-03-15",
                                  "2023-04-19"),
                         Topic = c(
                           paste0("[Introduction](", s_ohp_url, "20230315_ohp_l01.pdf)", collapse = ""),
                           paste0("[Model Selection and Variance Components](", s_ohp_url, "20230419_ohp_l02.pdf)", collapse = "")
                         ))
knitr::kable(tbl_ohp)

```

